export const themes = {
  default: {
    primaryColor: "#7749F8",
    secondaryColor: "#fff",
    bgColorHover: "#3f30dc",
    textColorHover: "#fff",
    primaryBackgroundColor: "#7749F8",
    secondaryBackgroundColor: "#f1f1f1",
    textFieldColorText: "white",
    textFieldColorBgHover: "rgba(255, 255, 255, 0.1)",
    textFieldColorLabel: "white",
    textFieldColorLabelHover: "#f1f1f1",
    textFieldColorLabelFocused: "#f1f1f1",
  },
  dark: {
    primaryColor: "black",
    secondaryColor: "white",
    bgColorHover: "#e3e3e3",
    textColorHover: "black",
    primaryBackgroundColor: "black",
    secondaryBackgroundColor: "#f1f1f1",
    textFieldColorText: "white",
    textFieldColorBgHover: "rgba(255, 255, 255, 0.1)",
    textFieldColorLabel: "white",
    textFieldColorLabelHover: "#f1f1f1",
    textFieldColorLabelFocused: "#f1f1f1",
  },
  yellowGreen: {
    primaryColor: "black",
    secondaryColor: "white",
    bgColorHover: "#e3e3e3",
    textColorHover: "black",
    primaryBackgroundColor: "black",
    secondaryBackgroundColor: "#f1f1f1",
    textFieldColorText: "white",
    textFieldColorBgHover: "rgba(255, 255, 255, 0.1)",
    textFieldColorLabel: "white",
    textFieldColorLabelHover: "#f1f1f1",
    textFieldColorLabelFocused: "#f1f1f1",
  },
};
